### ISSUE TITLE
Implement Builders RFC 0008: Jammy Builders

### ISSUE THREAD

**Issue by fg-j** [paketo-buildpacks/builder-jammy-full#1]
## Describe the Enhancement

Create a builder that allows users to build with most of the Paketo buildpacks on top of the Jammy base stack.

## Possible Solution

- [x] `builder.toml` that uses Jammy Base stack and the following buildpacks:
  - [x] dotnet-core https://github.com/paketo-buildpacks/dotnet-core/pull/737
  - [x] go https://github.com/paketo-buildpacks/go/issues/624
  - [x] java-native-image
  - [x] java
  - [x] nodejs https://github.com/paketo-buildpacks/nodejs/issues/607
  - [x] procfile
  - [x] python https://github.com/paketo-buildpacks/python/issues/490
  - [x] ruby https://github.com/paketo-buildpacks/ruby/issues/793
  - [x] web-servers https://github.com/paketo-buildpacks/web-servers/issues/85
  - [x] php https://github.com/paketo-buildpacks/php/issues/558
-  [x] smoke tests for each supported buildpack
- [x] full repo automation (see https://github.com/paketo-buildpacks/github-config/tree/main/builder)

## Motivation

Per [Builders RFC 0008](https://github.com/paketo-buildpacks/rfcs/blob/main/text/builders/0008-jammy-builders.md), Paketo wants to distribute a Jammy Full Builder that ultimately supports the same set of buildpacks as the Paketo Bionic Full Builder, but uses the Paketo Jammy Jellyfish stacks.

**Comment by fg-j** [comment]
Now that Nodejs supports jammy, @paketo-buildpacks/nodejs-maintainers please PR it into this builder with a smoke test!

**Comment by ForestEckhardt** [comment]
All buildpacks have been added!
